# Generated by Django 3.0 on 2023-07-21 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MovieApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movie', models.CharField(max_length=100)),
                ('moviename', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=100)),
                ('showtime', models.CharField(choices=[('11:00AM-1:30PM', '11:00AM-1:30PM'), ('2:30PM-5:00PM', '2:30PM-5:00PM'), ('5:30PM-8:00PM', '5:30PM-8:00PM'), ('8:30PM-11:00PM', '8:30PM-11:00PM')], default='0', max_length=100)),
                ('price', models.PositiveIntegerField(default=200)),
                ('is_avail', models.BooleanField(default=True)),
                ('usmovie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
